services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db_dictionary:
    container_name: db_dictionary
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_dictionary