server:
  port: 8085

spring:
  application:
    name: spring-boot-redis-cache

  data:
    redis:
      password: ""
      host: localhost
      port: 6379

  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/db_dictionary
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.default_schema: public
    show-sql: true